//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuicRemote.Host.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuicRemote.Host.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 当前控制者 的本地化字符串。
        /// </summary>
        internal static string ActiveControllerLabel {
            get {
                return ResourceManager.GetString("ActiveControllerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 码率 的本地化字符串。
        /// </summary>
        internal static string BitrateLabel {
            get {
                return ResourceManager.GetString("BitrateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户端已连接 的本地化字符串。
        /// </summary>
        internal static string ClientConnected {
            get {
                return ResourceManager.GetString("ClientConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户端已断开 的本地化字符串。
        /// </summary>
        internal static string ClientDisconnected {
            get {
                return ResourceManager.GetString("ClientDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户端 的本地化字符串。
        /// </summary>
        internal static string ClientsLabel {
            get {
                return ResourceManager.GetString("ClientsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编码器 的本地化字符串。
        /// </summary>
        internal static string CodecLabel {
            get {
                return ResourceManager.GetString("CodecLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已连接客户端 的本地化字符串。
        /// </summary>
        internal static string ConnectedClientsTitle {
            get {
                return ResourceManager.GetString("ConnectedClientsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制设备 ID 的本地化字符串。
        /// </summary>
        internal static string CopyDeviceIdToolTip {
            get {
                return ResourceManager.GetString("CopyDeviceIdToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备 ID 已复制! 的本地化字符串。
        /// </summary>
        internal static string DeviceIdCopied {
            get {
                return ResourceManager.GetString("DeviceIdCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备 ID 的本地化字符串。
        /// </summary>
        internal static string DeviceIdLabel {
            get {
                return ResourceManager.GetString("DeviceIdLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编码器设置 的本地化字符串。
        /// </summary>
        internal static string EncoderSettingsTitle {
            get {
                return ResourceManager.GetString("EncoderSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 授予控制权失败 的本地化字符串。
        /// </summary>
        internal static string FailedToGrantControl {
            get {
                return ResourceManager.GetString("FailedToGrantControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 撤销控制权失败 的本地化字符串。
        /// </summary>
        internal static string FailedToRevokeControl {
            get {
                return ResourceManager.GetString("FailedToRevokeControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启动失败 的本地化字符串。
        /// </summary>
        internal static string FailedToStart {
            get {
                return ResourceManager.GetString("FailedToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止失败 的本地化字符串。
        /// </summary>
        internal static string FailedToStop {
            get {
                return ResourceManager.GetString("FailedToStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帧率 的本地化字符串。
        /// </summary>
        internal static string FrameRateLabel {
            get {
                return ResourceManager.GetString("FrameRateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 授予控制权 的本地化字符串。
        /// </summary>
        internal static string GrantControlToolTip {
            get {
                return ResourceManager.GetString("GrantControlToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简体中文 的本地化字符串。
        /// </summary>
        internal static string LanguageChinese {
            get {
                return ResourceManager.GetString("LanguageChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        internal static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        internal static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 延迟 的本地化字符串。
        /// </summary>
        internal static string LatencyLabel {
            get {
                return ResourceManager.GetString("LatencyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示器 的本地化字符串。
        /// </summary>
        internal static string MonitorLabel {
            get {
                return ResourceManager.GetString("MonitorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无 的本地化字符串。
        /// </summary>
        internal static string NoneText {
            get {
                return ResourceManager.GetString("NoneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        internal static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 完全 的本地化字符串。
        /// </summary>
        internal static string PermissionFull {
            get {
                return ResourceManager.GetString("PermissionFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入 的本地化字符串。
        /// </summary>
        internal static string PermissionInput {
            get {
                return ResourceManager.GetString("PermissionInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无 的本地化字符串。
        /// </summary>
        internal static string PermissionNone {
            get {
                return ResourceManager.GetString("PermissionNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端口 的本地化字符串。
        /// </summary>
        internal static string PortLabel {
            get {
                return ResourceManager.GetString("PortLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 撤销控制权 的本地化字符串。
        /// </summary>
        internal static string RevokeControlToolTip {
            get {
                return ResourceManager.GetString("RevokeControlToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制者 的本地化字符串。
        /// </summary>
        internal static string RoleController {
            get {
                return ResourceManager.GetString("RoleController", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主机 的本地化字符串。
        /// </summary>
        internal static string RoleHost {
            get {
                return ResourceManager.GetString("RoleHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 观察者 的本地化字符串。
        /// </summary>
        internal static string RoleViewer {
            get {
                return ResourceManager.GetString("RoleViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 的本地化字符串。
        /// </summary>
        internal static string SettingsToolTip {
            get {
                return ResourceManager.GetString("SettingsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始共享 的本地化字符串。
        /// </summary>
        internal static string StartSharing {
            get {
                return ResourceManager.GetString("StartSharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        internal static string StatusLabel {
            get {
                return ResourceManager.GetString("StatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 准备就绪 的本地化字符串。
        /// </summary>
        internal static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行中 的本地化字符串。
        /// </summary>
        internal static string StatusRunning {
            get {
                return ResourceManager.GetString("StatusRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已停止 的本地化字符串。
        /// </summary>
        internal static string StatusStopped {
            get {
                return ResourceManager.GetString("StatusStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止共享 的本地化字符串。
        /// </summary>
        internal static string StopSharing {
            get {
                return ResourceManager.GetString("StopSharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 QuicRemote 主机 的本地化字符串。
        /// </summary>
        internal static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
